server:
  port: 8080

spring:  
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: idmoviesroute
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
        - id: idcatalogroute
          uri: lb://CATALOG-SERVICE
          predicates:
           - Path=/catalog/**
        
