server:
  port: 8080

spring:  
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: apiweatherroute
          uri: lb://WEATHER-SERVICE
          predicates:
            - Path=/api-weather/**
        - id: apiusuarioroute
          uri: lb://USUARIO-SERVICE
          predicates:
           - Path=/api-usuario/**
	  filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header

